using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net.Mail;
using System.Net.Mime;
using System.IO;
using System.Configuration;

namespace LRLogic
{
    public class SendEmail
    {
        public static void EmailSummary(string subject, string body, string totalFile, string processedFile, string rejectedFile)
        {
            MailMessage mail = new MailMessage();
            SmtpClient exchange = new SmtpClient(ConfigurationManager.AppSettings["MailExchange"].ToString());
            Attachment data1 = new Attachment(totalFile);
            Attachment data2 = new Attachment(processedFile);
            Attachment data3 = new Attachment(rejectedFile);
            mail.From = new MailAddress(ConfigurationManager.AppSettings["From"].ToString());
            mail.To.Add(new MailAddress(ConfigurationManager.AppSettings["To"].ToString()));
            //mail.To.Add(new MailAddress("OM_RECAUDOS"));
            //mail.CC.Add(new MailAddress(ConfigurationManager.AppSettings["CC"].ToString()));
            //mail.Bcc.Add(new MailAddress(ConfigurationManager.AppSettings["Bcc"].ToString()));
            mail.Attachments.Add(data1);
            mail.Attachments.Add(data2);
            mail.Attachments.Add(data3);
            mail.Subject = subject;
            mail.IsBodyHtml = true;
            mail.Body = body;
            mail.Priority = MailPriority.Normal;

            exchange.Send(mail);
            
            //File.Delete(totalFile);
            //File.Delete(processedFile);
            //File.Delete(rejectedFile);
        }

        public static string BuildEmail(string totalPaymentsProcessed, string totalRejectedPayments, string totalRecordsOnFile, string processedSummary, string rejectedSummary, double valid, double invalid)
        {
            string result = "";
            string paragraph = "<p></p>";
            string nextLine = "<br />";

            result += "This is an automated E-Mail generated by Lockbox, please do not reply to this message." + paragraph;
            result += "Total Payments Processed : " + totalPaymentsProcessed + paragraph;
            result += "Total Rejected Payments  : " + totalRejectedPayments + paragraph;
            result += "Total Records on File    : " + totalRecordsOnFile + paragraph;
            result += "Please post XXXXXXXXX to OpenSmartFlex under the Company Name [NEWC1]" + paragraph;
            result += "Process and Transaction files attached... ;)" + paragraph;
            result += "Processed Transaction Summary by Payment Method." + nextLine;
            result += "" + "" + processedSummary + nextLine;
            result += valid + nextLine;
            result += "Rejected Transaction Summary by Payment Method." + nextLine;
            result += "" + "" + rejectedSummary + nextLine;
            result += invalid + nextLine;
            result += "Payment Application Summary..." + paragraph;
            result += "Total Payments to be applied:  Total Payments Applied:  Total Payments Rejected: " + paragraph;
            result += "" + paragraph;

            return result;
        }
    }
}
